on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

name: Build Site

jobs:
  build-website:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Build site 🔧
        uses: quarto-dev/quarto-actions/render@v2

      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site